serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = 7000
auth.method = "token"
auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"

[[proxies]]
name = "udp1194"
type = "udp"
localIP = "127.0.0.1"
localPort = 1194
remotePort = 1194

[[proxies]]
name = "tcp80"
type = "tcp"
localIP = "192.168.1.211"
localPort = 80
remotePort = 8080

[[proxies]]
name = "tcp443"
type = "tcp"
localIP = "192.168.1.211"
localPort = 443
remotePort = 8443
