serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = 7000
auth.method = "token"
auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"

[[proxies]]
name = "tcp80"
type = "tcp"
localIP = "{{ .Envs.FRP_INGRESS_IP }}"
localPort = 80
remotePort = 8080

[[proxies]]
name = "tcp443"
type = "tcp"
localIP = "{{ .Envs.FRP_INGRESS_IP }}"
localPort = 443
remotePort = 8443
